[project]
name = "netbox-nsm"
version = "0.4.1"
description = "A NetBox plugin for documenting network security policy: rulebooks, zones, and NSM object links"
authors = [
    {name = "Christian Burmeister"},
]
license-files = ["LICENSE"]
readme = "README.md"
keywords = ["netbox", "netbox-plugin", "security"]
classifiers = [
    "Development Status :: 3 - Alpha",
]
dependencies = [
]
requires-python = ">=3.12"

[project.urls]
Homepage = "https://github.com/christianbur/netbox-nsm"
Documentation = "https://github.com/christianbur/netbox-nsm/blob/main/README.md"
Repository = "https://github.com/christianbur/netbox-nsm"
Issues = "https://github.com/christianbur/netbox-nsm/issues"

[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["examples*", "media*", "*.tests*"]

[tool.setuptools.package-data]
"netbox_nsm" = [
    "templates/**/*.html",
    "static/**/*",
    "plugin_assets/**/*",
    "schema/*.json",
    "locale/**/*.po",
]

[tool.black]
target-version = ["py312"]
