[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "netbox-nsm"
dynamic = ["version"]
description = "Initial minimal package to reserve the PyPI name."
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Christian Bur" }
]

[tool.setuptools.dynamic]
version = { attr = "netbox_nsm.__version__" }
