# Squashed initial migration for fresh empty-DB installs.
# Regenerate via docker/netbox_dev/scripts/generate_nsm_0001.sh when models change.
#
# Generated by Django 6.0.5 on 2026-06-11 04:32

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_custom_objects', '0014_fix_mixed_case_field_names'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotRulebook',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('parent_slug', models.SlugField(blank=True, default='', max_length=100)),
                ('matrix_tab_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'COT Rulebook',
                'verbose_name_plural': 'COT Rulebooks',
            },
        ),
        migrations.CreateModel(
            name='NsmUiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('menu_label', models.CharField(default='Security', max_length=100)),
                ('panel_label', models.CharField(default='Security', max_length=100)),
                ('setup_menu_dismissed', models.BooleanField(default=False)),
                ('setup_menu_config_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'NSM UI Settings',
                'verbose_name_plural': 'NSM UI Settings',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('custom_object_types', models.ManyToManyField(blank=True, related_name='nsm_sections', to='netbox_custom_objects.customobjecttype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'NSM Section',
                'verbose_name_plural': 'NSM Sections',
                'ordering': ('sort_order', 'slug'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CotRulebookAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('assigned_object_id', models.PositiveBigIntegerField()),
                ('cot_slug', models.SlugField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('assigned_object_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'dcim'), ('model', 'virtualdevicecontext')), models.Q(('app_label', 'virtualization'), ('model', 'virtualmachine')), _connector='OR')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Rulebook Assignment',
                'verbose_name_plural': 'Rulebook Assignments',
                'ordering': ('cot_slug', 'assigned_object_id'),
                'permissions': [('view_rulebook', 'Can view rulebooks'), ('add_rulebook', 'Can add rulebooks'), ('view_rulebookassignment', 'Can view rulebook assignments'), ('add_rulebookassignment', 'Can add rulebook assignments'), ('change_rulebookassignment', 'Can change rulebook assignments'), ('delete_rulebookassignment', 'Can delete rulebook assignments')],
                'indexes': [models.Index(fields=['assigned_object_type', 'assigned_object_id'], name='netbox_nsm__assigne_3a5a00_idx')],
                'constraints': [models.UniqueConstraint(fields=('assigned_object_type', 'assigned_object_id', 'cot_slug'), name='netbox_nsm_cotrulebookassignment_unique_cot_assignment')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('display_template', models.CharField(blank=True, default='{name}', max_length=255)),
                ('allow_virtual_groups', models.BooleanField(default=False)),
                ('inherit_links', models.BooleanField(default=False)),
                ('inherit_stop_on_own', models.BooleanField(default=False)),
                ('panel_linkable_types', models.JSONField(blank=True, default=list)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nsm_matching_configs', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Object Config',
                'verbose_name_plural': 'Object Configs',
                'ordering': ('sort_order', 'name', 'content_type__app_label', 'content_type__model'),
                'constraints': [models.UniqueConstraint(fields=('content_type',), name='netbox_nsm_typeconfig_content_type_uniq')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
