# Squashed initial migration for fresh empty-DB installs and upgrades from 0.4.1–0.4.2.
# Regenerate via docker/netbox_dev/scripts/generate_nsm_0001.sh when models change.
#
# Generated by Django 6.0.5 on 2026-06-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ("netbox_nsm", "0002_cotrulebook_row_group_by_col_id"),
        ("netbox_nsm", "0003_migrate_cotrulebook_to_nsm_config"),
        ("netbox_nsm", "0004_rulebook_permission_models"),
        ("netbox_nsm", "0005_consolidate_storage"),
        ("netbox_nsm", "0006_remove_rulebook_permission_anchor"),
        ("netbox_nsm", "0007_migrate_network_literal_to_comments"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RulebookListProxy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Rulebook",
                "verbose_name_plural": "Rulebooks",
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TypeConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Object Config",
                "verbose_name_plural": "Object Configs",
                "permissions": [
                    ("view_typeconfig", "Can view object configs"),
                    ("add_typeconfig", "Can add object configs"),
                    ("change_typeconfig", "Can change object configs"),
                    ("delete_typeconfig", "Can delete object configs"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
