# Generated by Django 6.0.5 on 2026-05-31 09:34

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_custom_objects", "0014_fix_mixed_case_field_names"),
        ("users", "0016_default_ordering_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NSMSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                (
                    "custom_object_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="nsm_sections",
                        to="netbox_custom_objects.customobjecttype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.owner",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "NSM Section",
                "verbose_name_plural": "NSM Sections",
                "ordering": ("sort_order", "slug"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SecurityArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.owner",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "ordering": ("sort_order", "slug"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="NSMTypeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "display_template",
                    models.CharField(blank=True, default="{name}", max_length=255),
                ),
                ("order_id", models.PositiveIntegerField(default=100)),
                ("allow_virtual_groups", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nsm_type_configs",
                        to="contenttypes.contenttype",
                        unique=True,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "areas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="type_configs",
                        to="netbox_nsm.securityarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "NSM Type Config",
                "verbose_name_plural": "NSM Type Configs",
                "ordering": (
                    "order_id",
                    "content_type__app_label",
                    "content_type__model",
                ),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SecurityObjectGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
                (
                    "areas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="object_groups",
                        to="netbox_nsm.securityarea",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.owner",
                    ),
                ),
                (
                    "sub_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent_groups",
                        to="netbox_nsm.securityobjectgroup",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Object Group",
                "verbose_name_plural": "Object Groups",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SecurityPolicyRulebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("rulebook_type", models.CharField(default="policy", max_length=20)),
                ("rule_comment_template", models.TextField(blank=True, default="")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.owner",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Policy",
                "verbose_name_plural": "Security Policies",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SecurityPolicyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("index", models.PositiveIntegerField(default=100)),
                ("enabled", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("log_enabled", models.BooleanField(default=False)),
                ("policy_action", models.CharField(default="permit", max_length=20)),
                ("virtual_group_config", models.JSONField(blank=True, default=dict)),
                (
                    "destination_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_destination_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.owner",
                    ),
                ),
                (
                    "source_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_source_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "rulebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="netbox_nsm.securitypolicyrulebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Rule",
                "verbose_name_plural": "Security Rules",
                "ordering": ("rulebook", "index", "name"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SecurityPolicyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("assigned_object_id", models.PositiveBigIntegerField()),
                (
                    "assigned_object_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(
                                models.Q(("app_label", "dcim"), ("model", "device")),
                                models.Q(
                                    ("app_label", "dcim"),
                                    ("model", "virtualdevicecontext"),
                                ),
                                models.Q(
                                    ("app_label", "virtualization"),
                                    ("model", "virtualmachine"),
                                ),
                                _connector="OR",
                            )
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "rulebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="netbox_nsm.securitypolicyrulebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Zone Rulebook assignment",
                "verbose_name_plural": "Security Zone Rulebook assignments",
                "ordering": ("rulebook", "assigned_object_id"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RulebookField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("placement", models.CharField(default="source", max_length=20)),
                (
                    "rulebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="netbox_nsm.securitypolicyrulebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rulebook Field",
                "verbose_name_plural": "Rulebook Fields",
                "ordering": ("rulebook", "sort_order", "slug"),
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicyRuleGroupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("exclude", models.BooleanField(default=False)),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rule_group_items",
                        to="netbox_nsm.rulebookfield",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_items",
                        to="netbox_nsm.securitypolicyrule",
                    ),
                ),
                (
                    "security_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_group_items",
                        to="netbox_nsm.securityobjectgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Group Item",
                "verbose_name_plural": "Rule Group Items",
                "ordering": (
                    "field__sort_order",
                    "field__slug",
                    "security_group__name",
                ),
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicyRuleObjectItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("exclude", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nsm_rule_items",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rule_object_items",
                        to="netbox_nsm.rulebookfield",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_items",
                        to="netbox_nsm.securitypolicyrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule Object Item",
                "verbose_name_plural": "Rule Object Items",
                "ordering": ("field__sort_order", "field__slug", "object_id"),
            },
        ),
        migrations.CreateModel(
            name="SecurityPropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only lowercase alphanumeric characters and underscores are allowed. Names may not start or end with an underscore, and double underscores are not permitted.",
                                regex="^[a-z0-9]+(_[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                ("verbose_name", models.CharField(blank=True, max_length=100)),
                ("verbose_name_plural", models.CharField(blank=True, max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "group_name",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("schema_document", models.JSONField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.owner",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "NSM Object Type",
                "verbose_name_plural": "NSM Object Types",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SecurityPropertyField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only lowercase alphanumeric characters and underscores are allowed. Names may not start or end with an underscore, and double underscores are not permitted.",
                                regex="^[a-z0-9]+(_[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                ("type", models.CharField(default="text", max_length=50)),
                ("group_name", models.CharField(blank=True, max_length=50)),
                ("required", models.BooleanField(default=False)),
                ("unique", models.BooleanField(default=False)),
                ("default", models.JSONField(blank=True, null=True)),
                ("weight", models.PositiveSmallIntegerField(default=100)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.owner",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "security_property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="netbox_nsm.securitypropertytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "NSM Object Type Field",
                "verbose_name_plural": "NSM Object Type Fields",
                "ordering": ("group_name", "weight", "name"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SecurityProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("name", models.CharField(max_length=150)),
                ("object_data", models.JSONField(blank=True, default=dict)),
                ("source_model", models.CharField(blank=True, max_length=64)),
                ("source_pk", models.PositiveBigIntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.owner",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "security_property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_propertys",
                        to="netbox_nsm.securitypropertytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "NSM Object",
                "verbose_name_plural": "NSM Objects",
                "ordering": ("security_property_type", "name"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TypeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "matching_class",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "display_template",
                    models.CharField(blank=True, default="{name}", max_length=255),
                ),
                ("allowed_placements", models.JSONField(blank=True, default=list)),
                (
                    "content_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nsm_type_config",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type Config",
                "verbose_name_plural": "Type Configs",
                "ordering": ("content_type__app_label", "content_type__model"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RulebookFieldType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("max_items", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_configs",
                        to="netbox_nsm.rulebookfield",
                    ),
                ),
                (
                    "type_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rulebook_field_types",
                        to="netbox_nsm.typeconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rulebook Field Type",
                "verbose_name_plural": "Rulebook Field Types",
                "ordering": ("field", "sort_order"),
            },
        ),
        migrations.CreateModel(
            name="NSMObjectLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("object_a_id", models.PositiveBigIntegerField()),
                ("object_b_id", models.PositiveBigIntegerField()),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "object_a_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "object_b_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "NSM Object Link",
                "verbose_name_plural": "NSM Object Links",
                "indexes": [
                    models.Index(
                        fields=["object_a_type", "object_a_id"],
                        name="netbox_nsm__object__256c33_idx",
                    ),
                    models.Index(
                        fields=["object_b_type", "object_b_id"],
                        name="netbox_nsm__object__d5ee26_idx",
                    ),
                ],
                "unique_together": {
                    ("object_a_type", "object_a_id", "object_b_type", "object_b_id")
                },
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SecurityObjectGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_items",
                        to="netbox_nsm.securityobjectgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Member",
                "verbose_name_plural": "Group Members",
                "ordering": ("group__name",),
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="netbox_nsm__content_af9d97_idx",
                    )
                ],
                "unique_together": {("group", "content_type", "object_id")},
            },
        ),
        migrations.AddConstraint(
            model_name="securitypolicyrule",
            constraint=models.UniqueConstraint(
                fields=("rulebook", "name"),
                name="netbox_nsm_securitypolicyrule_unique_rulebook_name",
            ),
        ),
        migrations.AddIndex(
            model_name="securitypolicyassignment",
            index=models.Index(
                fields=["assigned_object_type", "assigned_object_id"],
                name="netbox_nsm__assigne_d62d5f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="securitypolicyassignment",
            constraint=models.UniqueConstraint(
                fields=("assigned_object_type", "assigned_object_id", "rulebook"),
                name="netbox_nsm_securitypolicyassignment_unique_rulebook_assignment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rulebookfield",
            unique_together={("rulebook", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="securitypolicyrulegroupitem",
            unique_together={("rule", "field", "security_group")},
        ),
        migrations.AddIndex(
            model_name="securitypolicyruleobjectitem",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="netbox_nsm__content_6662ac_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="securitypolicyruleobjectitem",
            unique_together={("rule", "field", "content_type", "object_id")},
        ),
        migrations.AddConstraint(
            model_name="securitypropertytype",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="netbox_nsm_securitypropertytype_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="securitypropertyfield",
            constraint=models.UniqueConstraint(
                fields=("security_property_type", "name"),
                name="netbox_nsm_securitypropertyfield_unique_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityproperty",
            constraint=models.UniqueConstraint(
                fields=("security_property_type", "name"),
                name="netbox_nsm_securityproperty_unique_type_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityproperty",
            constraint=models.UniqueConstraint(
                fields=("security_property_type", "source_model", "source_pk"),
                name="netbox_nsm_securityproperty_unique_type_source",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rulebookfieldtype",
            unique_together={("field", "type_config")},
        ),
    ]
