# Generated by Django 6.0.5 on 2026-05-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_nsm', '0003_securityarea_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityarea',
            options={'ordering': ('sort_order', 'slug')},
        ),
        migrations.RemoveField(
            model_name='securitypolicyrule',
            name='action_groups',
        ),
        migrations.RemoveField(
            model_name='securitypolicyrule',
            name='custom_action_objects',
        ),
        migrations.RemoveField(
            model_name='securitypolicyrule',
            name='custom_service_objects',
        ),
        migrations.RemoveField(
            model_name='securitypolicyrule',
            name='custom_srcdst_objects',
        ),
        migrations.RemoveField(
            model_name='securitypolicyrule',
            name='destination_custom_objects',
        ),
        migrations.RemoveField(
            model_name='securitypolicyrule',
            name='destination_groups',
        ),
        migrations.RemoveField(
            model_name='securitypolicyrule',
            name='service_groups',
        ),
        migrations.RemoveField(
            model_name='securitypolicyrule',
            name='source_groups',
        ),
        migrations.AddField(
            model_name='securityarea',
            name='placement_mode',
            field=models.CharField(default='fixed', max_length=20),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('netbox_nsm', 'SecurityArea').objects.filter(
                slug__in=('srcdst', 'source', 'destination')
            ).update(placement_mode='directional'),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='SecurityPolicyRuleGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('placement', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_group_items', to='netbox_nsm.securityarea')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='netbox_nsm.securitypolicyrule')),
                ('security_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_group_items', to='netbox_nsm.securityobjectgroup')),
            ],
            options={
                'verbose_name': 'Rule Group Item',
                'verbose_name_plural': 'Rule Group Items',
                'ordering': ('area__sort_order', 'area__slug', 'placement', 'security_group__name'),
                'unique_together': {('rule', 'area', 'placement', 'security_group')},
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicyRuleObjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('placement', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_object_items', to='netbox_nsm.securityarea')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_items', to='netbox_nsm.securitypolicyrule')),
                ('security_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_object_items', to='netbox_nsm.securityobject')),
            ],
            options={
                'verbose_name': 'Rule Object Item',
                'verbose_name_plural': 'Rule Object Items',
                'ordering': ('area__sort_order', 'area__slug', 'placement', 'security_object__name'),
                'unique_together': {('rule', 'area', 'placement', 'security_object')},
            },
        ),
    ]
