# Generated by Django 6.0.5 on 2026-06-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_nsm", "0010_rulebookfieldtype_facet_mode"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="objectlink",
            new_name="netbox_nsm__propaga_b861c2_idx",
            old_name="netbox_nsm__propaga_idx",
        ),
        migrations.AddField(
            model_name="objectgroupmember",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="objectgroupmember",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="rulebookfield",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="rulebookfield",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="rulebookfieldtype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="rulebookfieldtype",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="rulegroupitem",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="rulegroupitem",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ruleobjectitem",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ruleobjectitem",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
