# Generated by Django 5.2.13 on 2026-05-13 12:28

import django.db.models.deletion
import ipam.fields
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0134_owner"),
        ("netbox_nsm", "0023_alter_securityzoneassignment_assigned_object_type"),
        ("tenancy", "0023_add_mptt_tree_indexes"),
        ("users", "0015_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="assigned_object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="assigned_object_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(("app_label", "ipam"), ("model", "prefix")),
                        models.Q(("app_label", "ipam"), ("model", "iprange")),
                        models.Q(("app_label", "ipam"), ("model", "ipaddress")),
                        models.Q(
                            ("app_label", "netbox_nsm"), ("model", "customprefix")
                        ),
                        _connector="OR",
                    )
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="CustomPrefix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("comments", models.TextField(blank=True)),
                ("prefix", ipam.fields.IPNetworkField()),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.owner",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_related",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["prefix"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prefix", "tenant"),
                        name="netbox_nsm_customprefix_unique_prefix",
                        violation_error_message="Prefix must be unique or unique within a tenant.",
                    )
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
