# Generated by Django 5.2.13 on 2026-05-13 12:31

from django.db import migrations


def migrate_address_to_gfk(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Address = apps.get_model("netbox_nsm", "Address")
    CustomPrefix = apps.get_model("netbox_nsm", "CustomPrefix")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # ContentType rows may not exist yet during some test DB migration flows.
    ip_range_ct = (
        ContentType.objects.using(db_alias)
        .filter(app_label="ipam", model="iprange")
        .first()
    )
    custom_prefix_ct = (
        ContentType.objects.using(db_alias)
        .filter(
            app_label="netbox_nsm",
            model="customprefix",
        )
        .first()
    )

    for instance in Address.objects.using(db_alias).all():
        update_fields = []

        # Option A: Route explicit ip_range rows
        if instance.ip_range_id:
            instance.assigned_object_id = instance.ip_range_id
            update_fields.append("assigned_object_id")

            if ip_range_ct:
                instance.assigned_object_type_id = ip_range_ct.id
                update_fields.append("assigned_object_type_id")

        # Option B: Convert legacy network strings into CustomPrefix rows
        elif instance.address:
            target_prefix, _ = CustomPrefix.objects.using(db_alias).get_or_create(
                prefix=instance.address
            )
            instance.assigned_object_id = target_prefix.id
            update_fields.append("assigned_object_id")

            if custom_prefix_ct:
                instance.assigned_object_type_id = custom_prefix_ct.id
                update_fields.append("assigned_object_type_id")

        if update_fields:
            instance.save(using=db_alias, update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_nsm", "0024_address_assigned_object_id_and_more"),
        ("ipam", "0086_gfk_indexes"),
    ]

    operations = [
        migrations.RunPython(
            migrate_address_to_gfk, reverse_code=migrations.RunPython.noop
        ),
    ]
