# Generated by Django 5.2.13 on 2026-05-14 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0134_owner"),
        ("netbox_nsm", "0025_route_address_fields_to_gfk"),
        ("tenancy", "0023_add_mptt_tree_indexes"),
        ("users", "0015_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ("name",)},
        ),
        migrations.RemoveField(
            model_name="address",
            name="address",
        ),
        migrations.RemoveField(
            model_name="address",
            name="ip_range",
        ),
        migrations.AlterField(
            model_name="address",
            name="assigned_object_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(("app_label", "ipam"), ("model", "prefix")),
                        models.Q(("app_label", "ipam"), ("model", "iprange")),
                        models.Q(("app_label", "ipam"), ("model", "ipaddress")),
                        models.Q(
                            ("app_label", "netbox_nsm"), ("model", "customprefix")
                        ),
                        _connector="OR",
                    )
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("assigned_object_id__isnull", False),
                        ("dns_name__isnull", True),
                    ),
                    models.Q(("assigned_object_id__isnull", False), ("dns_name", "")),
                    models.Q(
                        ("assigned_object_id__isnull", True),
                        ("dns_name__isnull", False),
                        models.Q(("dns_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="exclusive_assigned_object_or_dns_name",
            ),
        ),
    ]
