# Generated by Django 5.2.13 on 2026-05-15 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "netbox_nsm",
            "0026_alter_address_options_remove_address_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressassignment",
            name="assigned_object_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(("app_label", "dcim"), ("model", "device")),
                        models.Q(
                            ("app_label", "dcim"), ("model", "virtualdevicecontext")
                        ),
                        models.Q(
                            ("app_label", "virtualization"), ("model", "virtualmachine")
                        ),
                        models.Q(
                            ("app_label", "netbox_nsm"), ("model", "securityzone")
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="addresslistassignment",
            name="assigned_object_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(("app_label", "dcim"), ("model", "device")),
                        models.Q(
                            ("app_label", "dcim"), ("model", "virtualdevicecontext")
                        ),
                        models.Q(
                            ("app_label", "virtualization"), ("model", "virtualmachine")
                        ),
                        models.Q(
                            ("app_label", "netbox_nsm"), ("model", "securityzone")
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="addresssetassignment",
            name="assigned_object_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(("app_label", "dcim"), ("model", "device")),
                        models.Q(
                            ("app_label", "dcim"), ("model", "virtualdevicecontext")
                        ),
                        models.Q(
                            ("app_label", "virtualization"), ("model", "virtualmachine")
                        ),
                        models.Q(
                            ("app_label", "netbox_nsm"), ("model", "securityzone")
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="applicationassignment",
            name="assigned_object_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(("app_label", "dcim"), ("model", "device")),
                        models.Q(
                            ("app_label", "dcim"), ("model", "virtualdevicecontext")
                        ),
                        models.Q(
                            ("app_label", "virtualization"), ("model", "virtualmachine")
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="applicationsetassignment",
            name="assigned_object_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(("app_label", "dcim"), ("model", "device")),
                        models.Q(
                            ("app_label", "dcim"), ("model", "virtualdevicecontext")
                        ),
                        models.Q(
                            ("app_label", "virtualization"), ("model", "virtualmachine")
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="firewallfilterassignment",
            name="assigned_object_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(("app_label", "dcim"), ("model", "device")),
                        models.Q(
                            ("app_label", "dcim"), ("model", "virtualdevicecontext")
                        ),
                        models.Q(
                            ("app_label", "virtualization"), ("model", "virtualmachine")
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="policerassignment",
            name="assigned_object_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(
                        models.Q(("app_label", "dcim"), ("model", "device")),
                        models.Q(
                            ("app_label", "dcim"), ("model", "virtualdevicecontext")
                        ),
                        models.Q(
                            ("app_label", "virtualization"), ("model", "virtualmachine")
                        ),
                        _connector="OR",
                    )
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
