# Generated by Django 5.2.13 on 2026-05-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_nsm",
            "0027_alter_addressassignment_assigned_object_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customprefix",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s_set",
                "ordering": ["prefix"],
            },
        ),
    ]
