from django.db import migrations, models


FORWARD_SQL = """
DO $$
DECLARE
    constraint_name text;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'netbox_nsm_securityzonepolicy'
          AND column_name = 'source_zone_id'
    ) THEN
        CREATE TABLE IF NOT EXISTS public.netbox_nsm_securityzonepolicy_source_zone (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            securityzonepolicy_id bigint NOT NULL,
            securityzone_id bigint NOT NULL,
            CONSTRAINT netbox_nsm_securityz_securityzonepolicy_i_aad7f783_fk_netbox_ns
                FOREIGN KEY (securityzonepolicy_id)
                REFERENCES public.netbox_nsm_securityzonepolicy (id)
                DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT netbox_nsm_securityz_securityzone_id_370911f9_fk_netbox_ns
                FOREIGN KEY (securityzone_id)
                REFERENCES public.netbox_nsm_securityzone (id)
                DEFERRABLE INITIALLY DEFERRED
        );

        CREATE UNIQUE INDEX IF NOT EXISTS nb_nsm_szp_src_pol_zone_uix
            ON public.netbox_nsm_securityzonepolicy_source_zone (securityzonepolicy_id, securityzone_id);
        CREATE INDEX IF NOT EXISTS nb_nsm_szp_src_policy_ix
            ON public.netbox_nsm_securityzonepolicy_source_zone (securityzonepolicy_id);
        CREATE INDEX IF NOT EXISTS nb_nsm_szp_src_zone_ix
            ON public.netbox_nsm_securityzonepolicy_source_zone (securityzone_id);

        INSERT INTO public.netbox_nsm_securityzonepolicy_source_zone (securityzonepolicy_id, securityzone_id)
        SELECT id, source_zone_id
        FROM public.netbox_nsm_securityzonepolicy
        WHERE source_zone_id IS NOT NULL
        ON CONFLICT DO NOTHING;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'netbox_nsm_securityzonepolicy'
          AND column_name = 'destination_zone_id'
    ) THEN
        CREATE TABLE IF NOT EXISTS public.netbox_nsm_securityzonepolicy_destination_zone (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            securityzonepolicy_id bigint NOT NULL,
            securityzone_id bigint NOT NULL,
            CONSTRAINT netbox_nsm_securityz_securityzonepolicy_i_9ca094e3_fk_netbox_ns
                FOREIGN KEY (securityzonepolicy_id)
                REFERENCES public.netbox_nsm_securityzonepolicy (id)
                DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT netbox_nsm_securityz_securityzone_id_ee7e243b_fk_netbox_ns
                FOREIGN KEY (securityzone_id)
                REFERENCES public.netbox_nsm_securityzone (id)
                DEFERRABLE INITIALLY DEFERRED
        );

        CREATE UNIQUE INDEX IF NOT EXISTS nb_nsm_szp_dst_pol_zone_uix
            ON public.netbox_nsm_securityzonepolicy_destination_zone (securityzonepolicy_id, securityzone_id);
        CREATE INDEX IF NOT EXISTS nb_nsm_szp_dst_policy_ix
            ON public.netbox_nsm_securityzonepolicy_destination_zone (securityzonepolicy_id);
        CREATE INDEX IF NOT EXISTS nb_nsm_szp_dst_zone_ix
            ON public.netbox_nsm_securityzonepolicy_destination_zone (securityzone_id);

        INSERT INTO public.netbox_nsm_securityzonepolicy_destination_zone (securityzonepolicy_id, securityzone_id)
        SELECT id, destination_zone_id
        FROM public.netbox_nsm_securityzonepolicy
        WHERE destination_zone_id IS NOT NULL
        ON CONFLICT DO NOTHING;
    END IF;

    FOR constraint_name IN
        SELECT c.conname
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = 'public'
          AND t.relname = 'netbox_nsm_securityzonepolicy'
          AND c.contype = 'u'
          AND (
              pg_get_constraintdef(c.oid) ILIKE '%source_zone_id%'
              OR pg_get_constraintdef(c.oid) ILIKE '%destination_zone_id%'
          )
    LOOP
        EXECUTE format(
            'ALTER TABLE public.netbox_nsm_securityzonepolicy DROP CONSTRAINT IF EXISTS %I',
            constraint_name
        );
    END LOOP;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'netbox_nsm_securityzonepolicy'
          AND column_name = 'source_zone_id'
    ) THEN
        ALTER TABLE public.netbox_nsm_securityzonepolicy
            DROP COLUMN IF EXISTS source_zone_id CASCADE;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'netbox_nsm_securityzonepolicy'
          AND column_name = 'destination_zone_id'
    ) THEN
        ALTER TABLE public.netbox_nsm_securityzonepolicy
            DROP COLUMN IF EXISTS destination_zone_id CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = 'public'
          AND t.relname = 'netbox_nsm_securityzonepolicy'
          AND c.conname = 'netbox_nsm_securityzonepolicy_name_identifier_6a0a8a79_uniq'
    ) THEN
        ALTER TABLE public.netbox_nsm_securityzonepolicy
            ADD CONSTRAINT netbox_nsm_securityzonepolicy_name_identifier_6a0a8a79_uniq
            UNIQUE (name, identifier);
    END IF;
END
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_nsm", "0034_securityzone_roles_m2m"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(FORWARD_SQL, migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="securityzonepolicy",
                    name="source_zone",
                ),
                migrations.RemoveField(
                    model_name="securityzonepolicy",
                    name="destination_zone",
                ),
                migrations.AddField(
                    model_name="securityzonepolicy",
                    name="source_zone",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="source_zone_policies",
                        to="netbox_nsm.securityzone",
                    ),
                ),
                migrations.AddField(
                    model_name="securityzonepolicy",
                    name="destination_zone",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="destination_zone_policies",
                        to="netbox_nsm.securityzone",
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="securityzonepolicy",
                    unique_together={("name", "identifier")},
                ),
            ],
        ),
    ]
