# Generated by ChatGPT on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_nsm", "0047_objectgroup_group_member_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityzonepolicyrule",
            name="destination_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="securityzonepolicyrule_destination_groups",
                to="netbox_nsm.objectgroup",
            ),
        ),
        migrations.AddField(
            model_name="securityzonepolicyrule",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="securityzonepolicyrule",
            name="firewall_filters",
            field=models.ManyToManyField(
                blank=True,
                related_name="securityzonepolicyrule_firewall_filters",
                to="netbox_nsm.firewallfilter",
            ),
        ),
        migrations.AddField(
            model_name="securityzonepolicyrule",
            name="index",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="securityzonepolicyrule",
            name="log_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="securityzonepolicyrule",
            name="nat_rules",
            field=models.ManyToManyField(
                blank=True,
                related_name="securityzonepolicyrule_nat_rules",
                to="netbox_nsm.natrule",
            ),
        ),
        migrations.AddField(
            model_name="securityzonepolicyrule",
            name="policers",
            field=models.ManyToManyField(
                blank=True,
                related_name="securityzonepolicyrule_policers",
                to="netbox_nsm.policer",
            ),
        ),
        migrations.AddField(
            model_name="securityzonepolicyrule",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="securityzonepolicyrule_services",
                to="netbox_nsm.applicationitem",
            ),
        ),
        migrations.AddField(
            model_name="securityzonepolicyrule",
            name="source_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="securityzonepolicyrule_source_groups",
                to="netbox_nsm.objectgroup",
            ),
        ),
        migrations.AlterModelOptions(
            name="securityzonepolicyrule",
            options={
                "ordering": ("rulebook", "index", "name"),
                "verbose_name": "Security Rule",
                "verbose_name_plural": "Security Rules",
            },
        ),
    ]
