from django.urls import include, path

from utilities.urls import get_model_urls

from netbox_nsm.analyzers.object_analyzer.api_view import (
    AnalyzerAPIView,
    AnalyzerPickerAPIView,
)
from netbox_nsm.analyzers.object_analyzer.page_view import ObjectAnalyzerView
from netbox_nsm.analyzers.ip_analyzer.endpoints import (
    IpAnalyzerAddObjectTypesApiView,
    IpAnalyzerApiView,
    IpAnalyzerCategoryApiView,
    IpAnalyzerObjectDrilldownApiView,
)
from netbox_nsm.analyzers.object_report.views import ObjectReportView
from netbox_nsm.type_metadata.views import (
    TypeMetadataAddView,
    TypeMetadataDeleteView,
    TypeMetadataEditView,
    TypeMetadataListView,
    TypeMetadataView,
)
from netbox_nsm.bundles.views import (
    SetupSchemaApplyView,
    SetupSchemaDetailView,
    SetupSchemaPreviewView,
    SetupView,
)
from .views.plugin_static import PluginAssetView
from netbox_nsm.rulebooks.views.list import RulebookListView
from netbox_nsm.rulebooks.views.cot import (
    CotRulebookChangelogView,
    CotRulebookCreateView,
    CotRulebookDeleteView,
    CotRulebookMatrixView,
    CotRulebookRulesExportView,
    CotRulebookRulesView,
    CotRulebookSchemaValidateView,
    CotRulebookView,
)
from netbox_nsm.rulebooks.views.virtual_all import (
    AllRulesRulebookChangelogView,
    AllRulesRulebookContactsView,
    AllRulesRulebookJournalView,
    AllRulesRulebookRulesView,
    AllRulesRulebookView,
)
from netbox_nsm.security.object_link_config.views import (
    ObjectLinkConfigApplyView,
    ObjectLinkConfigEditView,
    ObjectLinkConfigPreviewView,
    ObjectLinkConfigView,
)
from netbox_nsm.security.views.inherited_links_api import InheritedLinksApiView
from netbox_nsm.security.views.object_link import (
    ObjectLinkAssignView,
    ObjectLinkDeleteView,
    ObjectLinkEditView,
    ObjectTypeElementsApiView,
)
from netbox_nsm.security.actions.confirm_views import (
    AddressIpamFkClearView,
    AddressIpamFkEditView,
    GroupM2mEditView,
    GroupM2mRemoveView,
)
from netbox_nsm.security.tab.security_views import make_co_security_view, make_host_security_view
from netbox_nsm.views.nsm_objects import (
    NsmCustomObjectBulkDeleteView,
    NsmCustomObjectBulkEditView,
    NsmCustomObjectBulkImportView,
    NsmCustomObjectChangeLogView,
    NsmCustomObjectDeleteView,
    NsmCustomObjectEditView,
    NsmCustomObjectJournalView,
    NsmCustomObjectListView,
    NsmCustomObjectView,
)

app_name = "netbox_nsm"

urlpatterns = [
    path(
        "assets/<path:asset_path>",
        PluginAssetView.as_view(),
        name="plugin_asset",
    ),
    path("bundles/", SetupView.as_view(), name="bundles"),
    path(
        "bundles/<slug:slug>/",
        SetupSchemaDetailView.as_view(),
        name="bundle_detail",
    ),
    path(
        "bundles/<slug:slug>/preview/",
        SetupSchemaPreviewView.as_view(),
        name="bundle_preview",
    ),
    path(
        "bundles/<slug:slug>/apply/",
        SetupSchemaApplyView.as_view(),
        name="bundle_apply",
    ),
    path("type-metadata/", TypeMetadataListView.as_view(), name="typemetadata_list"),
    path("type-metadata/add/", TypeMetadataAddView.as_view(), name="typemetadata_add"),
    path(
        "type-metadata/<slug:slug>/",
        TypeMetadataView.as_view(),
        name="typemetadata",
    ),
    path(
        "type-metadata/<slug:slug>/edit/",
        TypeMetadataEditView.as_view(),
        name="typemetadata_edit",
    ),
    path(
        "type-metadata/<slug:slug>/delete/",
        TypeMetadataDeleteView.as_view(),
        name="typemetadata_delete",
    ),
    path(
        "object-link-config/",
        ObjectLinkConfigView.as_view(),
        name="object_link_config",
    ),
    path(
        "object-link-config/edit/",
        ObjectLinkConfigEditView.as_view(),
        name="object_link_config_edit",
    ),
    path(
        "object-link-config/preview/",
        ObjectLinkConfigPreviewView.as_view(),
        name="object_link_config_preview",
    ),
    path(
        "object-link-config/apply/",
        ObjectLinkConfigApplyView.as_view(),
        name="object_link_config_apply",
    ),
    path("rulebooks/", RulebookListView.as_view(), name="rulebook_list"),
    path(
        "rulebooks/0/",
        AllRulesRulebookView.as_view(),
        name="all_rules_rulebook",
    ),
    path(
        "rulebooks/0/rules/",
        AllRulesRulebookRulesView.as_view(),
        name="all_rules_rules",
    ),
    path(
        "rulebooks/0/contacts/",
        AllRulesRulebookContactsView.as_view(),
        name="all_rules_contacts",
    ),
    path(
        "rulebooks/0/journal/",
        AllRulesRulebookJournalView.as_view(),
        name="all_rules_journal",
    ),
    path(
        "rulebooks/0/changelog/",
        AllRulesRulebookChangelogView.as_view(),
        name="all_rules_changelog",
    ),
    path(
        "rulebooks/cot/add/",
        CotRulebookCreateView.as_view(),
        name="cot_rulebook_add",
    ),
    path(
        "rulebooks/cot/add/validate-schema/",
        CotRulebookSchemaValidateView.as_view(),
        name="cot_rulebook_schema_validate",
    ),
    path(
        "rulebooks/cot/<slug:slug>/",
        CotRulebookView.as_view(),
        name="cot_rulebook",
    ),
    path(
        "rulebooks/cot/<slug:slug>/delete/",
        CotRulebookDeleteView.as_view(),
        name="cot_rulebook_delete",
    ),
    path(
        "rulebooks/cot/<slug:slug>/rules/export.json",
        CotRulebookRulesExportView.as_view(),
        name="cot_rulebook_rules_export",
    ),
    path(
        "rulebooks/cot/<slug:slug>/rules/",
        CotRulebookRulesView.as_view(),
        name="cot_rulebook_rules",
    ),
    path(
        "rulebooks/cot/<slug:slug>/matrix/",
        CotRulebookMatrixView.as_view(),
        name="cot_rulebook_matrix",
    ),
    path(
        "rulebooks/cot/<slug:slug>/changelog/",
        CotRulebookChangelogView.as_view(),
        name="cot_rulebook_changelog",
    ),
    path("api/ip-analyzer/", IpAnalyzerApiView.as_view(), name="ip_analyzer_api"),
    path(
        "api/ip-analyzer/category/",
        IpAnalyzerCategoryApiView.as_view(),
        name="ip_analyzer_category_api",
    ),
    path(
        "api/ip-analyzer/object/",
        IpAnalyzerObjectDrilldownApiView.as_view(),
        name="ip_analyzer_object_api",
    ),
    path(
        "api/ip-analyzer/add-object-types/",
        IpAnalyzerAddObjectTypesApiView.as_view(),
        name="ip_analyzer_add_object_types_api",
    ),
    path("object-analyzer/", ObjectAnalyzerView.as_view(), name="object_analyzer"),
    path("object-report/", ObjectReportView.as_view(), name="object_report"),
    path("api/analyzer/", AnalyzerAPIView.as_view(), name="analyzer_api"),
    path(
        "api/analyzer/picker/",
        AnalyzerPickerAPIView.as_view(),
        name="analyzer_picker_api",
    ),
    path(
        "api/inherited-links/",
        InheritedLinksApiView.as_view(),
        name="inherited_links_api",
    ),
    path(
        "api/type-elements/",
        ObjectTypeElementsApiView.as_view(),
        name="object_type_elements_api",
    ),
    path(
        "object-link/assign/",
        ObjectLinkAssignView.as_view(),
        name="object_link_assign",
    ),
    path(
        "object-link/<int:pk>/edit/",
        ObjectLinkEditView.as_view(),
        name="object_link_edit",
    ),
    path(
        "object-link/<int:pk>/delete/",
        ObjectLinkDeleteView.as_view(),
        name="object_link_delete",
    ),
    path(
        "panel-link/address-ipam-fk/<slug:slug>/clear/",
        AddressIpamFkClearView.as_view(),
        name="address_ipam_fk_clear",
    ),
    path(
        "panel-link/address-ipam-fk/<slug:slug>/edit/",
        AddressIpamFkEditView.as_view(),
        name="address_ipam_fk_edit",
    ),
    path(
        "panel-link/group-m2m/remove/",
        GroupM2mRemoveView.as_view(),
        name="group_m2m_remove",
    ),
    path(
        "panel-link/group-m2m/edit/",
        GroupM2mEditView.as_view(),
        name="group_m2m_edit",
    ),
    path(
        "objects/<str:custom_object_type>/",
        NsmCustomObjectListView.as_view(),
        name="nsm_object_list",
    ),
    path(
        "objects/<str:custom_object_type>/add/",
        NsmCustomObjectEditView.as_view(),
        name="nsm_object_add",
    ),
    path(
        "objects/<str:custom_object_type>/bulk-edit/",
        NsmCustomObjectBulkEditView.as_view(),
        name="nsm_object_bulk_edit",
    ),
    path(
        "objects/<str:custom_object_type>/bulk-delete/",
        NsmCustomObjectBulkDeleteView.as_view(),
        name="nsm_object_bulk_delete",
    ),
    path(
        "objects/<str:custom_object_type>/bulk-import/",
        NsmCustomObjectBulkImportView.as_view(),
        name="nsm_object_bulk_import",
    ),
    path(
        "objects/<str:custom_object_type>/<int:pk>/",
        NsmCustomObjectView.as_view(),
        name="nsm_object",
    ),
    path(
        "objects/<str:custom_object_type>/<int:pk>/edit/",
        NsmCustomObjectEditView.as_view(),
        name="nsm_object_edit",
    ),
    path(
        "objects/<str:custom_object_type>/<int:pk>/delete/",
        NsmCustomObjectDeleteView.as_view(),
        name="nsm_object_delete",
    ),
    path(
        "objects/<str:custom_object_type>/<int:pk>/journal/",
        NsmCustomObjectJournalView.as_view(),
        name="nsm_object_journal",
    ),
    path(
        "objects/<str:custom_object_type>/<int:pk>/changelog/",
        NsmCustomObjectChangeLogView.as_view(),
        name="nsm_object_changelog",
    ),
    path(
        "objects/<str:custom_object_type>/<int:pk>/security/",
        make_co_security_view().as_view(),
        name="nsm_object_security",
    ),
    path(
        "security/<str:app_label>/<str:model_name>/<int:pk>/",
        make_host_security_view().as_view(),
        name="host_security",
    ),
]
