from .schema import (
    NetBoxSecurityCustomPrefixQuery,
    NetBoxSecurityAddressQuery,
    NetBoxSecurityAddressSetQuery,
    NetBoxSecurityAddressListQuery,
    NetBoxSecurityApplicationItemQuery,
    NetBoxSecurityApplicationQuery,
    NetBoxSecurityApplicationSetQuery,
    NetBoxSecuritySecurityZoneQuery,
    NetBoxSecuritySecurityZonePolicyQuery,
    NetBoxSecurityNatPoolQuery,
    NetBoxSecurityNatPoolMemberQuery,
    NetBoxSecurityNatRuleSetQuery,
    NetBoxSecurityNatRuleQuery,
    NetBoxSecurityFirewallFilterQuery,
    NetBoxSecurityFirewallFilterRuleQuery,
    NetBoxSecurityPolicerQuery,
)

schema = [
    NetBoxSecurityCustomPrefixQuery,
    NetBoxSecurityAddressQuery,
    NetBoxSecurityAddressSetQuery,
    NetBoxSecurityAddressListQuery,
    NetBoxSecurityApplicationItemQuery,
    NetBoxSecurityApplicationQuery,
    NetBoxSecurityApplicationSetQuery,
    NetBoxSecuritySecurityZoneQuery,
    NetBoxSecuritySecurityZonePolicyQuery,
    NetBoxSecurityNatPoolQuery,
    NetBoxSecurityNatPoolMemberQuery,
    NetBoxSecurityNatRuleSetQuery,
    NetBoxSecurityNatRuleQuery,
    NetBoxSecurityFirewallFilterQuery,
    NetBoxSecurityFirewallFilterRuleQuery,
    NetBoxSecurityPolicerQuery,
]
