"""Address analysis — re-export surface for tests and legacy imports.

Public names without a leading underscore (e.g. ``build_multi_object_addr_analysis``)
are the stable API for views and services. Underscore-prefixed names remain for
unittest ``@patch("netbox_nsm.analyzers.ip_analyzer.addr_analysis_utils.*")`` compatibility.
"""

from __future__ import annotations

import builtins

from netbox_nsm.objects.type_config_specs import content_type_ids_for_cot_slugs

# Test patches target these names on this module (see test_addr_copy_paths / applet tests).
isinstance = builtins.isinstance

from netbox_nsm.analyzers.ip_analyzer.addr_constants import (
    _ADDR_IPAM_FK_FIELDS,
    _ADDR_IPAM_FK_FIELDS_HOST,
    _ADDR_IPAM_FK_FIELDS_SUBNET,
    _FIELD_TYPE_LABELS,
)

from netbox_nsm.analyzers.ip_analyzer.addr_ip_refs import (
    _addr_group_members,
    _addr_has_direct_ip_address,
    _addr_has_direct_range,
    _addr_ip_ref,
    _addr_ip_ref_field_order,
    _addr_ip_ref_from_fields,
    _addr_ip_ref_from_polymorphic_fk,
    _addr_ip_ref_node_dict,
    _addr_is_group_container,
    _addr_node_prefix_cidr,
    _attach_addr_node_prefix_display,
    _extract_ip_refs,
    _extract_ip_refs_visited,
    _ip_ref_dict,
    _ipam_fk_object_for_addr_node,
    _ipam_obj_from_ip_ref,
)

from netbox_nsm.analyzers.ip_analyzer.addr_navigation import (
    _addr_nav_append,
    _addr_nav_append_chain,
    _addr_nav_assigned_ips_in_prefix,
    _addr_nav_assigned_ips_in_range,
    _addr_nav_from_assigned,
    _addr_nav_object_link_hosts,
    _addr_navigation_refs,
    _attach_addr_navigation_refs,
    _host_ref_chain,
    _navigation_ref,
)

from netbox_nsm.analyzers.ip_analyzer.ipam_drilldown import (
    _attach_ipam_stats_meta,
    _attach_prefix_ipam_meta,
    _build_ipam_category_nodes,
    _build_ipam_prefix_layer_node,
    _build_ipam_prefix_resolve_nodes,
    _build_ipam_range_resolve_nodes,
    _collect_ipam_drilldown_children,
    _collect_ipam_prefix_children,
    _collect_ipam_prefix_children_impl,
    _collect_ipam_prefix_drilldown,
    _collect_ipam_prefix_ipam_children,
    _collect_ipam_range_ip_children,
    _filter_ipam_drilldown_category_nodes,
    _flatten_ipam_grouped,
    _ipam_analyzer_stat_label,
    _ipam_range_ip_count,
    _ipam_range_stats,
    _ip_count_from_ip_ref,
    _ipam_stats_ip_count,
    _ipam_stats_range_count,
    _ipam_stats_short,
    _ipam_stats_subnet_count,
    _ipam_stats_total,
    _is_ipam_addr_object,
    _lookup_ipam_prefix_from_ip_ref,
    _lookup_ipam_range_from_ip_ref,
    _ordered_ipam_stats,
    _prefix_ipam_stats,
    _prefix_is_large,
    _query_ipam_category_objects,
    _query_ipam_range_ip_objects,
    _resolve_ipam_stats_from_ip_ref,
)

from netbox_nsm.analyzers.ip_analyzer.addr_tree import (
    _addr_node_containment_map,
    _addr_path_line,
    _addr_path_parts_for_leaf,
    _addr_tree_child_visited,
    _addr_tree_network_covered,
    _addr_tree_node_display_count,
    _addr_tree_node_effective_network,
    _addr_tree_node_ip_count,
    _addr_tree_node_network,
    _addr_tree_node_range_count,
    _addr_tree_node_subnet_count,
    _build_addr_tree_node,
    _build_addr_tree_nodes,
    _display_count_for_addr_nodes,
    _enrich_addr_tree_copy_lines,
    _enrich_addr_tree_leaf_counts,
    _filter_non_contained_addr_nodes,
    _flatten_addr_tree_paths,
    _mark_contained_addr_duplicate_flags,
    _prefix_addr_copy_lines,
    _type_counts_for_addr_nodes,
)

from netbox_nsm.analyzers.ip_analyzer.addr_analyzable import (
    _object_is_addr_analyzable,
    _object_supports_addr_analysis,
)

from netbox_nsm.analyzers.ip_analyzer.addr_diff import (
    _addr_append_leaf_source,
    _addr_cross_side_name_conflict,
    _addr_diff_fund_detail,
    _addr_diff_fund_detail_multi,
    _addr_diff_fund_tooltip,
    _addr_entries_is_diff_fund,
    _addr_entry_is_diff_fund,
    _addr_leaf_compare_key,
    _addr_leaf_source_object,
    _addr_side_has_name_conflict,
    _addr_source_name_set,
    _addr_tree_node_prefix_compare_key,
    _build_addr_diff_analysis,
    _build_addr_diff_analysis_from_sides,
    _build_addr_diff_group,
    _build_diff_ipam_hierarchy_prefix_node,
    _build_diff_ipam_hierarchy_prefix_node_from_prefix,
    _build_diff_ipam_intersection_node,
    _build_diff_ipam_intersection_pair_node,
    _build_diff_ipam_intersection_tree,
    _build_diff_ipam_intersection_tree_multi,
    _collect_addr_tree_leaf_keys_under,
    _collect_addr_tree_leaf_map,
    _collect_addr_tree_prefix_groups,
    _compute_diff_prefix_hierarchy,
    _compute_diff_prefix_hierarchy_multi,
    _diff_ipam_prefix_for_intersection_node,
    _diff_status_for_exclusive_side,
    _enrich_diff_name_pill_fields,
    _intersection_node_compare_key,
    _lookup_containing_prefix_for_intersection_node,
    _lookup_ipam_prefix_for_cidr,
    _net_contains_ip_key,
    _prefix_group_to_diff_entry,
    _reorganize_diff_both_group_leaves,
    _reorganize_diff_ipam_intersection_tree,
    _reorganize_diff_leaves_under_prefix_hierarchy,
    _shallow_addr_leaf_for_diff,
    _suppress_diff_status_on_both_group_leaves,
    _type_counts_for_diff_addr_entry,
    _type_counts_for_diff_addr_keys,
    _type_counts_for_multi_diff,
)

from netbox_nsm.analyzers.ip_analyzer.addr_merge import (
    _apply_summary_type_counts_to_addr_analysis,
    _build_multi_object_addr_analysis,
    _count_addr_tree_duplicates,
    _count_ipa_object_tree_duplicates,
    _count_ipa_object_tree_group_duplicates,
    _ipa_object_tree_type_counts,
    _leaf_count_for_addr_analysis,
    _resolve_summary_type_counts,
    _type_counts_for_addr_analysis,
)

from netbox_nsm.analyzers.ip_analyzer.ipa_ipam_tree import (
    _build_ipa_object_drilldown_nodes,
    _build_ipa_object_ipam_tree,
)

from netbox_nsm.analyzers.ip_analyzer.ipa_object_node import (
    IPA_NODE_ROLE_GROUP,
    IPA_NODE_ROLE_HOST,
    IPA_NODE_ROLE_PREFIX,
    IPA_NODE_ROLE_RANGE,
    _ipa_object_node_presentation,
    _ipa_object_node_role_from_ip_ref,
)

from netbox_nsm.analyzers.ip_analyzer.ipa_object_tree import (
    _apply_object_tree_copy_lines,
    _attach_ipa_object_tree_ipam_stats,
    _attach_ipa_object_tree_ip_meta,
    _build_ipa_group_coverage,
    _build_ipa_cell_object_tree,
    _build_ipa_cell_object_tree_from_diff,
    _build_ipa_object_columns,
    _build_ipa_object_tree_node,
    _build_object_address_analysis,
    _collapse_ipa_cell_object_tree_roots,
    _collect_ipa_object_tree_keys,
    _enrich_ipa_node_from_resolved_prefix,
    _flatten_ipa_object_tree_copy_lines,
    _ipa_cell_object_tree_visible,
    _ipa_cell_tree_extended_summary_counts,
    _ipa_cidr_from_object_name,
    _ipa_deepest_cell_ancestor_node,
    _ipa_find_deepest_containing_node,
    _ipa_object_expands_members,
    _ipa_object_has_addr_drilldown,
    _ipa_object_tree_containment_cidr,
    _ipa_object_tree_csv_line,
    _ipa_object_tree_node_key,
    _ipa_object_tree_sort_key,
    _ipa_prefix_for_cell_object,
    _mark_ipa_cell_direct_flags,
    _mark_ipa_object_addr_drilldown_flags,
    _mark_ipa_object_tree_duplicate_flags,
    _mark_ipa_subnet_containment_warnings,
    _merge_ipa_cell_nodes_by_network,
    _parse_ipa_column_selections,
    _prune_ipa_object_tree_duplicate_nodes,
    _reorganize_ipa_object_tree_by_ipam_prefix_hierarchy,
    _sort_ipa_object_tree_siblings,
)

# Public stable API — underscore names above remain for unittest ``@patch`` targets.
apply_object_tree_copy_lines = _apply_object_tree_copy_lines
apply_summary_type_counts_to_addr_analysis = _apply_summary_type_counts_to_addr_analysis
build_addr_diff_analysis_from_sides = _build_addr_diff_analysis_from_sides
build_addr_tree_node = _build_addr_tree_node
build_ipa_object_drilldown_nodes = _build_ipa_object_drilldown_nodes
build_ipa_object_ipam_tree = _build_ipa_object_ipam_tree
build_multi_object_addr_analysis = _build_multi_object_addr_analysis
enrich_addr_tree_copy_lines = _enrich_addr_tree_copy_lines
enrich_addr_tree_leaf_counts = _enrich_addr_tree_leaf_counts
flatten_addr_tree_paths = _flatten_addr_tree_paths
filter_ipam_drilldown_category_nodes = _filter_ipam_drilldown_category_nodes
ipa_cell_object_tree_visible = _ipa_cell_object_tree_visible
leaf_count_for_addr_analysis = _leaf_count_for_addr_analysis
object_is_addr_analyzable = _object_is_addr_analyzable
object_supports_addr_analysis = _object_supports_addr_analysis
parse_ipa_column_selections = _parse_ipa_column_selections
prefix_ipam_stats = _prefix_ipam_stats
query_ipam_category_objects = _query_ipam_category_objects
resolve_summary_type_counts = _resolve_summary_type_counts

__all__ = (
    "apply_object_tree_copy_lines",
    "apply_summary_type_counts_to_addr_analysis",
    "build_addr_diff_analysis_from_sides",
    "build_addr_tree_node",
    "build_ipa_cell_object_tree",
    "build_ipa_object_drilldown_nodes",
    "build_ipa_object_ipam_tree",
    "build_multi_object_addr_analysis",
    "enrich_addr_tree_copy_lines",
    "enrich_addr_tree_leaf_counts",
    "flatten_addr_tree_paths",
    "filter_ipam_drilldown_category_nodes",
    "ipa_cell_object_tree_visible",
    "leaf_count_for_addr_analysis",
    "object_is_addr_analyzable",
    "object_supports_addr_analysis",
    "parse_ipa_column_selections",
    "prefix_ipam_stats",
    "query_ipam_category_objects",
    "resolve_summary_type_counts",
    "_addr_append_leaf_source",
    "_addr_cross_side_name_conflict",
    "_addr_diff_fund_detail",
    "_addr_diff_fund_detail_multi",
    "_addr_diff_fund_tooltip",
    "_addr_entries_is_diff_fund",
    "_addr_entry_is_diff_fund",
    "_addr_group_members",
    "_addr_has_direct_ip_address",
    "_addr_has_direct_range",
    "_addr_ip_ref",
    "_addr_ip_ref_field_order",
    "_addr_ip_ref_from_fields",
    "_addr_ip_ref_from_polymorphic_fk",
    "_addr_ip_ref_node_dict",
    "_addr_is_group_container",
    "_addr_leaf_compare_key",
    "_addr_leaf_source_object",
    "_addr_nav_append",
    "_addr_nav_append_chain",
    "_addr_nav_assigned_ips_in_prefix",
    "_addr_nav_assigned_ips_in_range",
    "_addr_nav_from_assigned",
    "_addr_nav_object_link_hosts",
    "_addr_navigation_refs",
    "_addr_node_containment_map",
    "_addr_node_prefix_cidr",
    "_addr_path_line",
    "_addr_path_parts_for_leaf",
    "_addr_side_has_name_conflict",
    "_addr_source_name_set",
    "_addr_tree_child_visited",
    "_addr_tree_network_covered",
    "_addr_tree_node_display_count",
    "_addr_tree_node_effective_network",
    "_addr_tree_node_ip_count",
    "_addr_tree_node_network",
    "_addr_tree_node_prefix_compare_key",
    "_addr_tree_node_range_count",
    "_addr_tree_node_subnet_count",
    "_apply_object_tree_copy_lines",
    "_apply_summary_type_counts_to_addr_analysis",
    "_attach_addr_navigation_refs",
    "_attach_addr_node_prefix_display",
    "_attach_ipa_object_tree_ipam_stats",
    "_attach_ipa_object_tree_ip_meta",
    "_attach_ipam_stats_meta",
    "_attach_prefix_ipam_meta",
    "_build_addr_diff_analysis",
    "_build_addr_diff_analysis_from_sides",
    "_build_addr_diff_group",
    "_build_addr_tree_node",
    "_build_addr_tree_nodes",
    "_build_diff_ipam_hierarchy_prefix_node",
    "_build_diff_ipam_hierarchy_prefix_node_from_prefix",
    "_build_diff_ipam_intersection_node",
    "_build_diff_ipam_intersection_pair_node",
    "_build_diff_ipam_intersection_tree",
    "_build_diff_ipam_intersection_tree_multi",
    "_build_ipa_cell_object_tree",
    "_build_ipa_cell_object_tree_from_diff",
    "_build_ipa_object_drilldown_nodes",
    "_build_ipa_object_ipam_tree",
    "_build_ipa_object_tree_node",
    "_build_ipam_category_nodes",
    "_build_ipam_prefix_layer_node",
    "_build_ipam_prefix_resolve_nodes",
    "_build_multi_object_addr_analysis",
    "_build_object_address_analysis",
    "_collapse_ipa_cell_object_tree_roots",
    "_collect_addr_tree_leaf_keys_under",
    "_collect_addr_tree_leaf_map",
    "_collect_addr_tree_prefix_groups",
    "_collect_ipa_object_tree_keys",
    "_collect_ipam_drilldown_children",
    "_collect_ipam_prefix_children",
    "_collect_ipam_prefix_children_impl",
    "_collect_ipam_prefix_drilldown",
    "_collect_ipam_prefix_ipam_children",
    "_collect_ipam_range_ip_children",
    "_compute_diff_prefix_hierarchy",
    "_compute_diff_prefix_hierarchy_multi",
    "_count_addr_tree_duplicates",
    "_count_ipa_object_tree_duplicates",
    "_count_ipa_object_tree_group_duplicates",
    "_diff_ipam_prefix_for_intersection_node",
    "_diff_status_for_exclusive_side",
    "_display_count_for_addr_nodes",
    "_enrich_addr_tree_copy_lines",
    "_enrich_addr_tree_leaf_counts",
    "_enrich_diff_name_pill_fields",
    "_enrich_ipa_node_from_resolved_prefix",
    "_extract_ip_refs",
    "_extract_ip_refs_visited",
    "_filter_non_contained_addr_nodes",
    "_flatten_addr_tree_paths",
    "_flatten_ipa_object_tree_copy_lines",
    "_flatten_ipam_grouped",
    "_host_ref_chain",
    "_intersection_node_compare_key",
    "_ip_ref_dict",
    "_ipa_cell_object_tree_visible",
    "_ipa_cidr_from_object_name",
    "_ipa_deepest_cell_ancestor_node",
    "_ipa_find_deepest_containing_node",
    "_ipa_object_expands_members",
    "_ipa_object_has_addr_drilldown",
    "_ipa_object_tree_containment_cidr",
    "_ipa_object_tree_csv_line",
    "_ipa_object_tree_node_key",
    "_ipa_object_tree_sort_key",
    "_ipa_object_tree_type_counts",
    "_ipa_prefix_for_cell_object",
    "_ipam_analyzer_stat_label",
    "_ipam_fk_object_for_addr_node",
    "_ipam_obj_from_ip_ref",
    "_ip_count_from_ip_ref",
    "_ipam_stats_ip_count",
    "_ipam_stats_range_count",
    "_ipam_stats_short",
    "_ipam_stats_subnet_count",
    "_ipam_stats_total",
    "_is_ipam_addr_object",
    "_leaf_count_for_addr_analysis",
    "_lookup_containing_prefix_for_intersection_node",
    "_lookup_ipam_prefix_for_cidr",
    "_lookup_ipam_prefix_from_ip_ref",
    "_lookup_ipam_range_from_ip_ref",
    "_mark_contained_addr_duplicate_flags",
    "_mark_ipa_cell_direct_flags",
    "_mark_ipa_object_addr_drilldown_flags",
    "_mark_ipa_object_tree_duplicate_flags",
    "_mark_ipa_subnet_containment_warnings",
    "_merge_ipa_cell_nodes_by_network",
    "_navigation_ref",
    "_net_contains_ip_key",
    "_object_is_addr_analyzable",
    "_object_supports_addr_analysis",
    "_ordered_ipam_stats",
    "_parse_ipa_column_selections",
    "_prefix_addr_copy_lines",
    "_prefix_group_to_diff_entry",
    "_prefix_ipam_stats",
    "_prefix_is_large",
    "_query_ipam_category_objects",
    "_reorganize_diff_both_group_leaves",
    "_reorganize_diff_ipam_intersection_tree",
    "_reorganize_diff_leaves_under_prefix_hierarchy",
    "_reorganize_ipa_object_tree_by_ipam_prefix_hierarchy",
    "_resolve_ipam_stats_from_ip_ref",
    "_resolve_summary_type_counts",
    "_sort_ipa_object_tree_siblings",
    "_shallow_addr_leaf_for_diff",
    "_suppress_diff_status_on_both_group_leaves",
    "_type_counts_for_addr_analysis",
    "_type_counts_for_addr_nodes",
    "_type_counts_for_diff_addr_entry",
    "_type_counts_for_diff_addr_keys",
    "_type_counts_for_multi_diff",
)
