"""Address diff analysis (multi-side comparison).

Implementation lives in ``addr_diff_collect``, ``addr_diff_fund``,
``addr_diff_hierarchy``, and ``addr_diff_build``. This module is the stable
import surface for ``addr_analysis_utils`` and tests.
"""

from netbox_nsm.analyzers.ip.addr_diff_build import (
    _build_addr_diff_analysis,
    _build_addr_diff_analysis_from_sides,
    _diff_status_for_exclusive_side,
)
from netbox_nsm.analyzers.ip.addr_diff_collect import (
    _addr_append_leaf_source,
    _addr_leaf_compare_key,
    _addr_leaf_source_object,
    _addr_source_name_set,
    _addr_tree_node_prefix_compare_key,
    _collect_addr_tree_leaf_keys_under,
    _collect_addr_tree_leaf_map,
    _collect_addr_tree_prefix_groups,
    _compute_diff_prefix_hierarchy,
    _compute_diff_prefix_hierarchy_multi,
    _lookup_ipam_prefix_for_cidr,
    _prefix_group_to_diff_entry,
)
from netbox_nsm.analyzers.ip.addr_diff_fund import (
    _addr_cross_side_name_conflict,
    _addr_diff_fund_detail,
    _addr_diff_fund_detail_multi,
    _addr_diff_fund_tooltip,
    _addr_entries_is_diff_fund,
    _addr_entry_is_diff_fund,
    _addr_side_has_name_conflict,
    _enrich_diff_name_pill_fields,
    _shallow_addr_leaf_for_diff,
)
from netbox_nsm.analyzers.ip.addr_diff_hierarchy import (
    _build_addr_diff_group,
    _build_diff_ipam_hierarchy_prefix_node,
    _build_diff_ipam_hierarchy_prefix_node_from_prefix,
    _build_diff_ipam_intersection_node,
    _build_diff_ipam_intersection_pair_node,
    _build_diff_ipam_intersection_tree,
    _build_diff_ipam_intersection_tree_multi,
    _diff_ipam_prefix_for_intersection_node,
    _intersection_node_compare_key,
    _lookup_containing_prefix_for_intersection_node,
    _net_contains_ip_key,
    _reorganize_diff_both_group_leaves,
    _reorganize_diff_ipam_intersection_tree,
    _reorganize_diff_leaves_under_prefix_hierarchy,
    _suppress_diff_status_on_both_group_leaves,
    _type_counts_for_diff_addr_entry,
    _type_counts_for_diff_addr_keys,
    _type_counts_for_multi_diff,
)

__all__ = (
    "_addr_append_leaf_source",
    "_addr_cross_side_name_conflict",
    "_addr_diff_fund_detail",
    "_addr_diff_fund_detail_multi",
    "_addr_diff_fund_tooltip",
    "_addr_entries_is_diff_fund",
    "_addr_entry_is_diff_fund",
    "_addr_leaf_compare_key",
    "_addr_leaf_source_object",
    "_addr_side_has_name_conflict",
    "_addr_source_name_set",
    "_addr_tree_node_prefix_compare_key",
    "_build_addr_diff_analysis",
    "_build_addr_diff_analysis_from_sides",
    "_build_addr_diff_group",
    "_build_diff_ipam_hierarchy_prefix_node",
    "_build_diff_ipam_hierarchy_prefix_node_from_prefix",
    "_build_diff_ipam_intersection_node",
    "_build_diff_ipam_intersection_pair_node",
    "_build_diff_ipam_intersection_tree",
    "_build_diff_ipam_intersection_tree_multi",
    "_collect_addr_tree_leaf_keys_under",
    "_collect_addr_tree_leaf_map",
    "_collect_addr_tree_prefix_groups",
    "_compute_diff_prefix_hierarchy",
    "_compute_diff_prefix_hierarchy_multi",
    "_diff_ipam_prefix_for_intersection_node",
    "_diff_status_for_exclusive_side",
    "_enrich_diff_name_pill_fields",
    "_intersection_node_compare_key",
    "_lookup_containing_prefix_for_intersection_node",
    "_lookup_ipam_prefix_for_cidr",
    "_net_contains_ip_key",
    "_prefix_group_to_diff_entry",
    "_reorganize_diff_both_group_leaves",
    "_reorganize_diff_ipam_intersection_tree",
    "_reorganize_diff_leaves_under_prefix_hierarchy",
    "_shallow_addr_leaf_for_diff",
    "_suppress_diff_status_on_both_group_leaves",
    "_type_counts_for_diff_addr_entry",
    "_type_counts_for_diff_addr_keys",
    "_type_counts_for_multi_diff",
)
