name: Lint

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@main

          - name: Check conformance to Black standards
            uses: psf/black@stable
            with:
                options: "--check"
                src: "netbox_nsm"
