name: Test with NetBox

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    test-netbox:
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis
                ports:
                  - 6379:6379

            postgres:
                image: postgres
                env:
                    POSTGRES_USER: netbox
                    POSTGRES_PASSWORD: netbox
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                  - 5432:5432

        steps:
          - name: Checkout code
            uses: actions/checkout@main
            with:
                path: netbox-nsm

          - name: Checkout netbox-custom-objects
            uses: actions/checkout@main
            with:
                repository: netboxlabs/netbox-custom-objects
                path: netbox-custom-objects

          - name: Set up Python 3.12
            uses: actions/setup-python@main
            with:
                python-version: "3.12"

          - name: Checkout NetBox
            uses: actions/checkout@main
            with:
                repository: "netbox-community/netbox"
                path: netbox
                ref: main

          - name: Install plugins
            run: |
                python -m pip install --upgrade pip
                python -m pip install tblib
                # include tests directories for test discovery
                sed -i 's/exclude/#exclude/g' netbox-nsm/pyproject.toml
                if [ -f netbox-custom-objects/pyproject.toml ]; then
                  sed -i 's/exclude/#exclude/g' netbox-custom-objects/pyproject.toml
                fi
                pip install ./netbox-custom-objects
                pip install ./netbox-nsm

          - name: Set up configuration
            working-directory: netbox
            run: |
                ln -s $(pwd)/../netbox-nsm/media/configuration.testing.py netbox/netbox/configuration.py
                pip install -r requirements.txt -U

          - name: Legacy import check
            working-directory: netbox-nsm
            run: ./scripts/check_legacy_imports.sh

          - name: Run tests
            working-directory: netbox
            run: |
                python netbox/manage.py migrate netbox_custom_objects --no-input
                python netbox/manage.py migrate netbox_nsm --no-input
                python netbox/manage.py test netbox_nsm.tests --parallel -v2
